name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    env:
      PORT: ${{ secrets.PORT }}
      MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_URI }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
      
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      
      - name: Set up environment variables
        run: |
          echo "PORT=${{ env.PORT }}" >> .env
          echo "MONGODB_URI=${{ env.MONGODB_URI }}" >> .env    
          echo "AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}" >> .env
          echo "CORS_ORIGIN=${{ env.CORS_ORIGIN }}" >> .env

      - name: Verify Environment Variables
        run: node verify-env.js
        
      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build --if-present
        
      - name: Start Application
        run: pm2 restart init
          